name: Server Test Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC to runs every 7-8 min set cron to '*/1 * * * *'
  workflow_dispatch:   # manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main 

    - name: Create file and commit
      run: |
        FILE="commit_number.md"
        if [ ! -f "$FILE" ]; then
          echo "Daily Server Wellness Check - Successful" > "$FILE"
          echo "commit number: 1" >> "$FILE"
        else
          CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")
          if [ -z "$CURRENT_COUNT" ]; then
            CURRENT_COUNT=0
          fi
          NEXT_COUNT=$((CURRENT_COUNT + 1))
          sed -i "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
        fi
        git config --global user.name "jiacheh4"
        git config --global user.email "jiacheh4@berkeley.edu"
        git add "$FILE"
        git commit -m "Daily Server Wellness Check"
        git push https://x-access-token:${{ secrets.test_server_auto_commit_token }}@github.com/FfangAI/test-server.git
      env:
        GITHUB_TOKEN: ${{ secrets.test_server_auto_commit_token }}